namespace Essenbee.Z80.Spectrum48
{
    public enum KeyCode
    {
        Q, W, E, R, T, Y, U, I, O, P, A, S, D, F, G, H, J, K, L, Z, X, C, V, B, N, M,
        _0, _1, _2, _3, _4, _5, _6, _7, _8, _9,
        SPACE, SHIFT, CTRL, ALT, TAB, CAPS, ENTER, BACK,
        DEL, INS, HOME, END, PGUP, PGDOWN, NUMLOCK,
        ESC, PRINT_SCREEN, SCROLL_LOCK, PAUSE_BREAK,
        TILDE, EXCLAMATION, AT, HASH, DOLLAR, PERCENT, CARAT,
        AMPERSAND, ASTERISK, LBRACKET, RBRACKET, HYPHEN, PLUS, VBAR,
        LCURLY, RCURLY, COLON, DQUOTE, LESS_THAN, GREATER_THAN, QMARK,
        UNDER_SCORE, EQUALS, BSLASH, LSQUARE, RSQUARE, SEMI_COLON,
        APOSTROPHE, COMMA, STOP, FSLASH, LEFT, RIGHT, UP, DOWN,
        F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12,
        LAST
    };
}